### ISSUE TITLE
Bot can add reminders for dates that have already occured

### ISSUE THREAD

**Issue by SpaceKatt** [Chris-Johnston/CSSBot#32] opened 2019-02-05 21:47 UTC
![feb05 134620](https://user-images.githubusercontent.com/10052234/52306333-84932580-294c-11e9-8f70-b45e056acecb.png)

**Comment by Chris-Johnston** [comment] 2019-02-05 21:48
no u

**Comment by Chris-Johnston** [comment] 2019-02-06 21:45
Duplicate of #28

**Closed as completed by Chris-Johnston** 2019-02-06 21:45 UTC
Labels: invalid
